DROP TABLE IF EXISTS LSE_LIBRARY_BOOKS;
DROP TABLE IF EXISTS LSE_LIBRARY_LOCATIONS;
DROP TABLE IF EXISTS LSE_LIBRARY_SHELFS;
DROP TABLE IF EXISTS LSE_LIBRARY_STACKS;



CREATE TABLE `LSE_LIBRARY_BOOKS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ISBN_NO` varchar(255) DEFAULT NULL,
  `STACK_NO` varchar(4) DEFAULT NULL,
  `SHELF_NO` varchar(2) DEFAULT NULL,
  `LOCATION_NO` varchar(3) DEFAULT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `AUTHOR` varchar(255) DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  `TIME_CREATED` time DEFAULT NULL,
  `DATE_UPDATED` date DEFAULT NULL,
  `TIME_UPDATED` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDX_ISBN` (`ISBN_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LSE_LIBRARY_LOCATIONS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATION_NO` varchar(3) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  `TIME_CREATED` time DEFAULT NULL,
  `DATE_UPDATED` date DEFAULT NULL,
  `TIME_UPDATED` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LSE_LIBRARY_SHELFS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SHELF_NAME` varchar(255) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LSE_LIBRARY_STACKS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STACK_NO` varchar(4) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

